insert into Towar (nazwa, cena, opis) values ('Fib N9 - Prague Powder', 29.99, 'Non-prs chr ulcer oth prt unsp low leg lmt to brkdwn skin');
insert into Towar (nazwa, cena, opis) values ('Bouillion - Fish', 86.52, 'Mech compl of unspecified vascular grafts, subs encntr');
insert into Towar (nazwa, cena, opis) values ('Flour - Pastry', 50.09, 'Unspecified blepharoconjunctivitis, left eye');
insert into Towar (nazwa, cena, opis) values ('Devonshire Cream', 41.66, 'Disp fx of med phalanx of l rng fngr, 7thD');
insert into Towar (nazwa, cena, opis) values ('Butter - Pod', 16.29, 'Oth diab with prolif diabetic rtnop with macular edema, unsp');
insert into Towar (nazwa, cena, opis) values ('Mushroom - Morels, Dry', 70.55, 'Unsp fracture of left ilium, subs for fx w nonunion');
insert into Towar (nazwa, cena, opis) values ('Quail - Whole, Boneless', 5.1, 'Struck by softball, initial encounter');
insert into Towar (nazwa, cena, opis) values ('Chick Peas - Canned', 9.21, 'Hemorrhoids in pregnancy, third trimester');
insert into Towar (nazwa, cena, opis) values ('Tamarillo', 32.85, 'Bullous impetigo');
insert into Towar (nazwa, cena, opis) values ('Lobster - Tail, 3 - 4 Oz', 39.72, 'Disp fx of posterior wall of unspecified acetabulum, sequela');
insert into Towar (nazwa, cena, opis) values ('Veal - Ground', 41.57, 'Crushing injury of unspecified left toe(s), init encntr');
insert into Towar (nazwa, cena, opis) values ('Caviar - Salmon', 25.07, 'Papyraceous fetus, third trimester, other fetus');
insert into Towar (nazwa, cena, opis) values ('Pasta - Cannelloni, Sheets, Fresh', 99.91, 'Persistent cloaca');
insert into Towar (nazwa, cena, opis) values ('Apron', 70.9, 'Infect/inflm reaction due to internal right knee prosthesis');
insert into Towar (nazwa, cena, opis) values ('Eggroll', 5.4, 'Disp fx of med phalanx of r less toe(s), 7thG');
insert into Towar (nazwa, cena, opis) values ('Cornflakes', 82.82, 'Burn of 2nd deg mul sites of shldr/up lmb, except wrs/hnd');
insert into Towar (nazwa, cena, opis) values ('Scallop - St. Jaques', 70.52, 'Allergic contact dermatitis due to cosmetics');
insert into Towar (nazwa, cena, opis) values ('Wine - Red, Gamay Noir', 99.17, 'Struck by falling object on oth powered watercraft, sequela');
insert into Towar (nazwa, cena, opis) values ('Bay Leaf', 10.5, 'Struck by chicken');
insert into Towar (nazwa, cena, opis) values ('Oven Mitts - 15 Inch', 58.29, 'Nondisp fx of med condyle of unsp tibia, 7thG');
insert into Towar (nazwa, cena, opis) values ('Drambuie', 71.9, 'Jumping or diving into swimming pool striking wall');
insert into Towar (nazwa, cena, opis) values ('Wine - Barossa Valley Estate', 69.41, 'Fracture of other parts of neck, initial encounter');
insert into Towar (nazwa, cena, opis) values ('Rice - Jasmine Sented', 3.89, 'Inj extensor musc/fasc/tend l idx fngr at wrs/hnd lv, init');
insert into Towar (nazwa, cena, opis) values ('Oysters - Smoked', 44.15, 'Unsp injury of musc/fasc/tend prt biceps, left arm, subs');
insert into Towar (nazwa, cena, opis) values ('Ocean Spray - Ruby Red', 23.56, 'Nondisp oblique fx shaft of humer, r arm, init for opn fx');
insert into Towar (nazwa, cena, opis) values ('Bagel - Whole White Sesame', 67.73, 'Embolism and thrombosis of other thoracic veins');
insert into Towar (nazwa, cena, opis) values ('Cocoa Powder - Dutched', 51.35, 'Antepartum hemorrhage w oth coag defect, first trimester');
insert into Towar (nazwa, cena, opis) values ('Wine - Merlot Vina Carmen', 74.21, 'Strain extensor musc/fasc/tend r little finger at wrs/hnd lv');
insert into Towar (nazwa, cena, opis) values ('Wine - Alsace Gewurztraminer', 96.99, 'Fall on same level, unspecified, subsequent encounter');
insert into Towar (nazwa, cena, opis) values ('Tart Shells - Sweet, 4', 41.67, 'Car driver injured in collision w car nontraf, subs');
insert into Towar (nazwa, cena, opis) values ('Salmon - Whole, 4 - 6 Pounds', 16.15, 'Infect/inflm reaction due to int fix of unsp site');
insert into Towar (nazwa, cena, opis) values ('Chocolate Bar - Smarties', 34.07, 'Displ spiral fx shaft of unsp femr, 7thJ');
insert into Towar (nazwa, cena, opis) values ('Tea - Decaf 1 Cup', 53.48, 'Encounter for fit/adjst of non-vascular catheter');
insert into Towar (nazwa, cena, opis) values ('Cheese - Oka', 27.9, 'Unsp fracture of T7-T8 vertebra, subs for fx w delay heal');
insert into Towar (nazwa, cena, opis) values ('Poppy Seed', 47.47, 'Burn third deg of unsp site right low limb, ex ank/ft, init');
insert into Towar (nazwa, cena, opis) values ('Muffin Hinge Container 6', 93.89, 'Subluxation of distal interphaln joint of l idx fngr, init');
insert into Towar (nazwa, cena, opis) values ('Tea - English Breakfast', 53.5, 'Monteggia''s fx r ulna, 7thF');
insert into Towar (nazwa, cena, opis) values ('Rice - 7 Grain Blend', 49.14, 'Displ Maisonneuve''s fx unsp leg, 7thF');
insert into Towar (nazwa, cena, opis) values ('Flour - Rye', 75.32, 'Oth fracture of right femur, subs for clos fx w nonunion');
insert into Towar (nazwa, cena, opis) values ('Rum - Coconut, Malibu', 40.14, 'Personal history of (corrected) congenital malform of ear');
insert into Towar (nazwa, cena, opis) values ('Red Snapper - Fresh, Whole', 51.92, 'Pasngr on bus injured in clsn w nonmtr vehicle in traf, subs');
insert into Towar (nazwa, cena, opis) values ('Mountain Dew', 90.59, 'Toxic eff of nitrodrv/aminodrv of benzn/homolog, undet, subs');
insert into Towar (nazwa, cena, opis) values ('Coffee Cup 12oz 5342cd', 88.58, 'Other shock');
insert into Towar (nazwa, cena, opis) values ('Wine - Red, Mosaic Zweigelt', 4.8, 'Other articular cartilage disorders');
insert into Towar (nazwa, cena, opis) values ('Pork - Belly Fresh', 86.72, 'Other osteomyelitis, unspecified sites');
insert into Towar (nazwa, cena, opis) values ('Muffin Hinge - 211n', 5.83, 'Other myositis, other site');
insert into Towar (nazwa, cena, opis) values ('Wine - Manischewitz Concord', 11.22, 'Asphyx due to being trapped in a car trunk, slf-hrm, sequela');
insert into Towar (nazwa, cena, opis) values ('Mortadella', 89.09, 'Pedestrian injured in collision w car, pick-up truck or van');
insert into Towar (nazwa, cena, opis) values ('Lemonade - Mandarin, 591 Ml', 60.92, 'Poisoning by oth parasympath, accidental, init');
insert into Towar (nazwa, cena, opis) values ('Cheese - Camembert', 90.34, 'Nondisplaced unsp fracture of right lesser toe(s), sequela');
insert into Towar (nazwa, cena, opis) values ('Olive - Spread Tapenade', 7.55, 'Drug/chem diabetes mellitus w ketoacidosis w/o coma');
insert into Towar (nazwa, cena, opis) values ('Banana', 88.26, 'Corrosion of second degree of right hand, unsp site, subs');
insert into Towar (nazwa, cena, opis) values ('Rum - Cream, Amarula', 60.93, 'Enteropathy-type (intestinal) T-cell lymphoma');
insert into Towar (nazwa, cena, opis) values ('Table Cloth 120 Round White', 46.42, 'Disp fx of nk of 2nd MC bone, r hand, subs for fx w nonunion');
insert into Towar (nazwa, cena, opis) values ('Passion Fruit', 43.43, 'Toxic effect of cobra venom, accidental, init');
insert into Towar (nazwa, cena, opis) values ('Coriander - Ground', 58.37, 'Sltr-haris Type II physeal fx lower end of right femur');
insert into Towar (nazwa, cena, opis) values ('Chinese Foods - Chicken', 47.7, 'Rupture of synovium');
insert into Towar (nazwa, cena, opis) values ('Rabbit - Saddles', 44.84, 'Adrenogenital disorders');
insert into Towar (nazwa, cena, opis) values ('Muffin Mix - Banana Nut', 87.41, 'Ped on foot inj pick-up truck, pk-up/van nontraf, sequela');
insert into Towar (nazwa, cena, opis) values ('Turnip - White, Organic', 46.61, 'Toxic effect of mycotoxin food contamnt, undetermined, subs');
insert into Towar (nazwa, cena, opis) values ('Mayonnaise - Individual Pkg', 47.23, 'Unspecified viral hepatitis C');
insert into Towar (nazwa, cena, opis) values ('Sesame Seed Black', 80.6, 'Other specified diseases of pancreas');
insert into Towar (nazwa, cena, opis) values ('Wine - Chablis 2003 Champs', 41.96, 'Drug/chem diab w mod nonprlf diab rtnop w/o macular edema');
insert into Towar (nazwa, cena, opis) values ('Lettuce - Escarole', 38.33, 'Nondisp fx of head of r rad, 7thM');
insert into Towar (nazwa, cena, opis) values ('Wine - Lamancha Do Crianza', 29.7, 'Displ commnt fx shaft of r tibia, 7thE');
insert into Towar (nazwa, cena, opis) values ('Potato - Sweet', 40.57, 'Contus/lac l cereb w LOC >24 hr w/o ret consc w surv, init');
insert into Towar (nazwa, cena, opis) values ('C - Plus, Orange', 8.72, 'Displ spiral fx shaft of ulna, l arm, 7thP');
insert into Towar (nazwa, cena, opis) values ('Guinea Fowl', 91.7, 'Paralytic calcifcn and ossifictn of muscle, unsp lower leg');
insert into Towar (nazwa, cena, opis) values ('Jack Daniels', 42.31, 'Acquired absence of upper limb above wrist');
insert into Towar (nazwa, cena, opis) values ('Juice - V8, Tomato', 52.34, 'Other injury of ovary, unilateral, initial encounter');
insert into Towar (nazwa, cena, opis) values ('Soup - Campbells Bean Medley', 64.34, 'Nondisp fx of lateral condyle of r tibia, 7thD');
insert into Towar (nazwa, cena, opis) values ('Island Oasis - Wildberry', 70.6, 'Other specified injuries of unspecified foot');
insert into Towar (nazwa, cena, opis) values ('Bread - Hamburger Buns', 3.74, 'Pnctr of abd wl w/o fb, epigst rgn w/o penet perit cav, init');
insert into Towar (nazwa, cena, opis) values ('Vinegar - Red Wine', 20.71, 'Fall from other pedestrian conveyance, sequela');
insert into Towar (nazwa, cena, opis) values ('Tart Shells - Sweet, 4', 82.69, 'Diseases of the nervous system complicating childbirth');
insert into Towar (nazwa, cena, opis) values ('Basil - Dry, Rubbed', 10.28, 'Enlargement of bilateral orbits');
insert into Towar (nazwa, cena, opis) values ('Prunes - Pitted', 22.5, 'Displ oblique fx shaft of unsp tibia, 7thF');
insert into Towar (nazwa, cena, opis) values ('Crush - Cream Soda', 31.0, 'Nondisp suprcndl fx w intrcndl extn low end unsp femr, 7thE');
insert into Towar (nazwa, cena, opis) values ('Coriander - Seed', 18.08, 'Laceration of ulnar artery at wrist and hand level');
insert into Towar (nazwa, cena, opis) values ('Croissant, Raw - Mini', 55.17, 'Xanthelasma of right lower eyelid');
insert into Towar (nazwa, cena, opis) values ('Glucose', 77.18, 'Aortic ectasia, unspecified site');
insert into Towar (nazwa, cena, opis) values ('Rosemary - Primerba, Paste', 38.48, 'Displ simp suprcndl fx w/o intrcndl fx l humer, 7thD');
insert into Towar (nazwa, cena, opis) values ('Wine - Ej Gallo Sonoma', 67.9, 'Disp fx of lateral condyle of l tibia, 7thQ');
insert into Towar (nazwa, cena, opis) values ('Lettuce - Lambs Mash', 7.63, 'Displaced fracture of navicular [scaphoid] of left foot');
insert into Towar (nazwa, cena, opis) values ('Tart - Butter Plain Squares', 67.3, 'Malignant neoplasm of anterior wall of nasopharynx');
insert into Towar (nazwa, cena, opis) values ('Wine - Cabernet Sauvignon', 20.4, 'Acute gastritis');
insert into Towar (nazwa, cena, opis) values ('Shrimp - 16 - 20 Cooked, Peeled', 81.87, 'Nondisp avuls fracture (chip fracture) of right talus, init');
insert into Towar (nazwa, cena, opis) values ('Tuna - Canned, Flaked, Light', 59.38, 'Malignant neoplasm of cervix uteri, unspecified');
insert into Towar (nazwa, cena, opis) values ('Island Oasis - Cappucino Mix', 91.15, 'Contus/lac cereb, w LOC of 31-59 min, sequela');
insert into Towar (nazwa, cena, opis) values ('Muffin - Mix - Creme Brule 15l', 30.6, 'Toxic effect of carbon monoxide from motor vehicle exhaust');
insert into Towar (nazwa, cena, opis) values ('Pork - Tenderloin, Fresh', 89.46, 'Unsp car occ inj in clsn with statnry object nontraf, init');
insert into Towar (nazwa, cena, opis) values ('Egg - Salad Premix', 17.91, 'Incomplete lesion of L1 level of lumbar spinal cord, init');
insert into Towar (nazwa, cena, opis) values ('Puree - Kiwi', 43.85, 'Poisoning by oth estrogens and progstrn, accidental, subs');
insert into Towar (nazwa, cena, opis) values ('Wine - Red, Pinot Noir, Chateau', 53.49, 'Laceration of dorsal vein of left foot, sequela');
insert into Towar (nazwa, cena, opis) values ('Wine - Trimbach Pinot Blanc', 98.46, 'Displ avuls fx (chip fracture) of r talus, 7thK');
insert into Towar (nazwa, cena, opis) values ('Cheese - St. Paulin', 68.22, 'Otitis media, unspecified');
insert into Towar (nazwa, cena, opis) values ('Veal - Knuckle', 66.42, 'Oth physeal fx upper end of l fibula, subs for fx w nonunion');
insert into Towar (nazwa, cena, opis) values ('Trueblue - Blueberry', 99.44, '3-part fx surg neck of r humerus, subs for fx w delay heal');
insert into Towar (nazwa, cena, opis) values ('Beef - Rib Roast, Capless', 20.21, 'Unspecified fracture of head of unspecified femur, sequela');
insert into Towar (nazwa, cena, opis) values ('Rice Wine - Aji Mirin', 99.53, 'Maternal care for damage to fetus by oth medical proc, unsp');
